import type {Metadata} from "next";
import "material-symbols/rounded.css"
import "./globals.css";
import NavIsland from "@/app/components/nav-island";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="font-Sofia antialiased">
        <NavIsland/>
        {children}
        </body>
        </html>
    );
}
