import type {Metadata} from "next";
import "material-symbols/rounded.css"
import "./globals.css";
import NavIsland from "@/app/components/nav-island";
import {ClientLayout, LayoutProps} from "@/app/(restaurants)/client-layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<LayoutProps>) {
    return (
        <html lang="en">
        <body className="font-Sofia antialiased">
        <ClientLayout {...props} />
        </body>
        </html>
    );
}
